# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'starbucksClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SkyFloatingLabelTextField', '~> 3.0'
  # Pods for starbucksClone

  target 'starbucksCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'starbucksCloneUITests' do
    # Pods for testing
  end

end
